ASKBOT/askbot-devel

- askbot/media/js/utils.js
currently there's an error thrown if you try to edit comment and then cancel it by pressing escape button. `Uncaught TypeError: Cannot read property 'preventDefault' of undefined`
this happens because `EditCommentForm.prototype.getCancelHandler()` is used for both click handler and keyup handler where it tries to do evt.preventDefault();
this fixes it.
> pass event object through makeKeyHandler

- askbot/media/js/post.js
- askbot/media/js/utils.js
- askbot/media/js/utils/autocompleter.js
- askbot/media/js/utils/two_state_toggle.js
- gulpfile.js
Instead of replacing the label with the error, the error gets inserted after the label.
I also added Bootstrap form error class to the from-group, to have bootstrap styling.
Further I fixed all the current javascript validation errors
> Form Errors should not delete the label completely

- askbot/conf/site_settings.py
- askbot/conf/words.py
- askbot/templates/widgets/user_navigation.html
Created new askbot setting for the login/signup link text (defaulted to the string that used to be in the template) and use it in the template.
Trello ticket: [Can we change "Hi there! Please sign in" to "Click here to log in or register"](
https://trello.com/c/EqSRly6G/558-can-we-change-hi-there-please-sign-in-to-click-here-to-log-in-or-register)
> New askbot setting: text for the login/signup hyperlink

- package.json
To compile the js with closure-compiler we need it as a requirement.
*Note* ClosureCompiler works for all askbot custom javascript, but not with the dependencies.
We can not use the compiled js version yet, because that some jsfiles are throwing errors, when the required dom elements are not found
> add gulp-closure-compiler to requirements

- askbot/media/js/tag_selector.js
We use uniform.js to style radio button, which is listening to the events of the radio.
But since you unbind click events here: https://github.com/ASKBOT/askbot-devel/blob/master/askbot/media/js/tag_selector.js#L358
Uniform is not getting updated on Internet Explorer and Firefox
> Trigger other events bind to the radio

- askbot/media/js/group_messaging.js
- askbot/media/js/utils/autocompleter.js
The request for the autocomplete on recipients is getting cached.
If I want to add "paulo" and then "diana" to recipients, I can only find paulo.
Only cache the request, if cache is enabled. Do not cache it for group messaging
> autocomplete on create new message

- askbot/conf/access_control.py
- askbot/deps/group_messaging/views.py
- askbot/setup_templates/settings.py
- askbot/views/users.py
We want to give admins access to all users inboxes:
There is now a setting under: /settings/ACCESS_CONTROL/
Default value is false to not backward compatibility.
> Allow Admin users to access other users inbox

- askbot/media/js/post.js
cancelRetag was not triggered on document click because `click()` doesn't accept second param the way `addEventListener` does.
now that it's working I also stopped propagation on autocomplete results because if you click on them cancelRetag would be triggered
also added ability to modify the form through triggering an event
> fix incorrect handling of events in questionRetagger

- askbot/templates/widgets/ask_button.html
Merge this commit if you want the button text to be WORDS_ASK_THE_GROUP when variable 'group' is set and/or when variable 'default_ask_group_id' is set, and only fall back to WORDS_ASK_YOUR_QUESTION when neither 'group' nor 'default_ask_group_id' is set.
Currently (without this commit), the button text is WORDS_ASK_THE_GROUP when variable 'group' is set, otherwise the button text is WORDS_ASK_YOUR_QUESTION (even if default_ask_group_id is set).
> Use WORDS_ASK_THE_GROUP when 'default_ask_group_id' template variable is set even if 'group' isn't.

- askbot/media/js/group_messaging.js
- askbot/templates/group_messaging/home.html
Currently the only way to go back to threads list is to click on a tab `received/sent/trash`.
This PR adds back button near compose message button that's visible then it's possible to go back.
> add back button functionality in inbox

- askbot/media/js/utils/lang_nav.js
Mainly this PR addresses missing semicolon on line 53.
When compress is enabled and files are concatenated into one it gets concatenated with timeago.js which starts with `(` which results in a function call which in turn breaks the page.
> add missing semicolons

- askbot/models/__init__.py
without this, when django first loads askbot, it will do this registration which will then call ```get_user_model()``` when using django >= 1.5 , ```get_user_model()``` will then load all django apps again to find the "custom user model" and once done then continue loading the askbot models file.
The scenario above causes many problems, for one it makes askbot's loading order irrelevant because it will always load at the end of all apps regardless of where it is in ```INSTALLED_APPS```, two models that depend on the askbot User model patch will raise ```AttributeErrors``` because askbot's User model has not finished loading since it's the last app.
> moves followit registration to bottom of models.

- askbot/migrations/0184_auto__add_field_post_renderer.py
- askbot/models/post.py
This PR allows to set the renderer to be used for each Post and allows to override post renderers with custom implementation from the settings.
By default the behavior is unchanged and backwards compatible.
> Add a renderer field to be able to override the default renderer

- askbot/mail/parsing.py
Fixed bug where emails from Tim's Mac mail client (with no quoted text) were being truncated - if they were 3 lines or less, they were causing creation of blank answers/comments.
Better to risk including undesirable text in answers/comments than risk not including important text that should be
there. 
Also improved logging a bit.
> Fix for emails from Mac email client

- askbot/views/readers.py
...not just the ones for the questions on the current page.
> Show the tags for all questions on the homepage

- askbot/conf/vote_rules.py
- askbot/models/__init__.py
Instead of comparing the difference in day of month now and when vote was created, compare the actual time delta in days.
Also added possibility to disable the time limit by setting the MAX_DAYS_TO_CANCEL_VOTE to -1.
> Fix vote cancel timeout check and allow disabling it

- askbot/conf/settings_wrapper.py
If there is cache connection failures, cache.get() will return None even if the same cache value was just set. And also it's more efficient to return the just generated dict instead of taking the round trip through cache.
> Do not return None if cache does not respond

- askbot/const/__init__.py
- askbot/views/commands.py
Refactor the askbot.views.commands.vote view. The view still follows the same logic and should still be refactored (e.g. commands split into individual views and exceptions not used for flow control), but the business logic is now easier to follow.
As part of the refactoring, the check for authenticated users is now performed [at the top of the view](https://github.com/ASKBOT/askbot-devel/compare/master...divio:votes-view-refactoring?expand=1#diff-44f5682d65647031237f28c6a3149339R150) for all actions and as such prevents some errors (e.g. AnonymousUser has not attribute flag_post). A consequence of this is that in case of unauthenticated users the response message is [generic](https://github.com/ASKBOT/askbot-devel/compare/master...divio:votes-view-refactoring?expand=1#diff-44f5682d6564703 …
> Refactoring the askbot.views.commands.vote view

- askbot/utils/forms.py
Using the `ASKBOT_URL` setting always redirects to the default language, instead of redirecting to the currently active language.
> Correctly reverse default url when calling get_next_url

- askbot/deps/django_authopenid/forms.py
- askbot/utils/decorators.py
- askbot/utils/forms.py
- askbot/utils/functions.py
Spotted some calls referencing hard strings instead of lazy translations, causing these strings to use the language active when they are first used.
> Lazy translations

- askbot/models/question.py
Otherwise, it breaks when multiple languages have the same Tag
because the Get will return multiple results.
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>
> Query tags by language

- askbot/search/haystack/signals.py
I only override this on ```handle_delete``` because I'm assuming the thread object gets updated every time a post is updated, contrary to when a post is deleted.
Overriding this on ```handle_save``` could cause the thread object to be indexed multiple times for no reason.
> remove thread when post removed

- askbot/const/__init__.py
choices for the status field of class User).
Presumably it used to be in there at some point because there are loads
of pieces of code that behave as if it's a valid value for the
user.status field.
For example:
* askbot/models/__init__.py's user_set_status function checks that the
supplied new_status is in ('d', 'm', 's', 'b', 'w', 'a'), and its
make_admin_if_first_user function calls user.set_status('d').
* askbot/forms.py's ChangeUserStatusForm is provided with this as one of
the valid choices.
* etc...
> Added ('d', _('administrator')) to USER_STATUS_CHOICES (ie the tuple of

- askbot/templates/macros.html
Will impact .po translation files, but I'm unable to run makemessages on my instance so I leave that to somebody else. Any non-English translations of msgid "Waiting approval" are likely to still be valid for "Awaiting approval", so probably just a matter of removing the fuzzy markers.
> Fixed typo - "Waiting approval" should be "Awaiting approval".

- askbot/media/wmd/wmd.js
otherwise throws error ``Cannot set property onpaste of null`` in chrome and various others.
only happened when editor did not exist on the page (e.g. user not logged in)
> check for input existence, and only then start working with it

- askbot/auth.py
- askbot/models/__init__.py
- askbot/search/haystack/signals.py
- askbot/signals.py
* Rename ``delete_question_or_answer`` to ``after_post_removed``
* Correct the ``delete_by`` argument (right name is ``deleted_by``)
* Add ``after_post_restored`` to handle post restoration
* Fire signals from ``user_restore_post``
* Fire signals from ``onFlaggedItem`` and ``onUnflaggedItem``
> Improve signals handling for post deletion

- askbot/models/__init__.py
Badge awards can be triggered in the context of a different user (e.g.
when he votes on a post) and as such, we need to make sure that the
language of the notification of the user matches its settings and not
the currently active language of the user executing the triggering
action.
> Use the user primary language when delivering badge messages

- askbot/utils/forms.py
Fixed this so that it works for emails like 'username+somealias@gmail.com' which contain special regex characters (+ in this case) - don't see why the over-complicated regex is required anyway.
> Simplification and handle gmail alias email addresses.

- askbot/mail/lamson_handlers.py
lamson_handlers.py now logs that it's running (and the time), and when processing a VALIDATION, logs the username, not just the from address (which will not always be the same as the user's email).
> More logging by lamson_handlers.py

- askbot/admin.py
Will only take effect if you put 'avatar' *before* 'askbot' in INSTALLED_APPS list (we only define and
register it if avatar module's own version has already been registered,
otherwise when that comes to be registered there'll be an
AlreadyRegistered exception). If django_avatar not installed, does nothing.
> Better django admin list view for Avatar model

- askbot/models/question.py
No need to not pass user if it's None or anonymous because the method that actually ends up using the user object does the right thing itself.
> Simplified Thread method get_answers

- askbot/media/js/live_search.js
the event is helpful if one wants to track search submit via google analytics or an alternative tool
> search submit event

- askbot/deps/livesettings/models.py
- askbot/setup_templates/settings.py
- askbot/setup_templates/settings.py.mustache
Changing `CACHE_BACKEND` to `memcached://127.0.0.1:11211/` has no effect at all anymore with django 1.8.
> Use modern django cache configuration in settings

- .gitignore
KP instances (with lamson mail processing) - and probably(?) other instances of askbot - have a directory called 'logs' at the root level - get git to ignore this directory.
> Git ignore directory 'logs' at root level.

- askbot/models/__init__.py
- askbot/models/post.py
- askbot/models/question.py
... so that it no longer ignores private 'answer' Posts. Also partly fixes "Block user and delete all content" so that it deletes private as well as public answers (fix for questions to follow).
https://trello.com/c/ALfA5KCO/822-use-correct-last-activity-info-when-deleting-answer-for-a-private-question and https://trello.com/c/EWOVfvrK/879-block-user-and-delete-all-content-doesn-t-delete-private-questions-answers
> Fix Thread.update_last_activity_info method

- askbot/deps/django_authopenid/util.py
- askbot/deps/django_authopenid/views.py
Previously the provider name lookup of an openid provider during
login process was handled by the get_provider_name() call. This
call just simply extract the domain name from the returned
openid_url, and cannot fully identify different endpoint
settings of an openid provider. For example on our staging
site we are using https://openstackid-dev.openstackid.org,
meanwhile on production site the openid_endpoint url
just simply the https://openstackid.org.
This patch adds the ability to lookup the provider endpoint
settings defined in util.py's get_enabled_major_login_providers().
To provide compatibility with previous implementations, when a
the lookup not results a matching provider name, it fall
back to previous get_provider_name().
> Fix openid provider name lookup

- askbot/deps/livesettings/models.py
- askbot/deps/livesettings/tests.py
- askbot/deps/livesettings/urls.py
- askbot/deps/livesettings/views.py
https://trello.com/c/lHa8ehJU/735-settings-export-to-be-in-yaml-format
Evgeny, the code that handles the language-specific settings (_create_language_hierarchy) is only applicable to Askbot. Should this go outside of the livesettings code?
> Yaml export

- askbot/views/commands.py
"exceptions must be old-style classes or derived
from BaseException, not HttpResponseBadRequest"
This was masking another error where the Knowledgepoint template context processor was missing from the settings file
> Fixed misleading error message when hitting subscribe button

- askbot/views/widgets.py
https://trello.com/c/s0ebwVHd/9-private-questions-appear-in-question-list-widget-to-anon-users-and-users-who-are-not-in-the-groups
> Questions list widget now limits to threads that are visible to the current user

- askbot/forms.py
Each time it was submitted, it caused all the Spaces corresponding to the ASKBOT_AGGREGATOR_SITE_IDS to be added to the Thread!
https://trello.com/c/Rcr5TlF9/989-post-at-partner-sites-form-always-adds-main-kp-space-to-thread-whether-it-was-listed-ticked-in-form-or-not
> Stop the unexpected side-effect of the 'Post at partner sites' form

- askbot/management/commands/askbot_setup_sites.py
We carefully configure which Spaces should auto-aggregate to main site,
and allow users with adequate permissions to share individual Threads
with other Spaces, so we don't ever want to blindly add all Threads to
main Space. I think this is legacy code that no longer makes sense. Also
updated/clarified some of the instructions in comments at top.
https://trello.com/c/s3ymUcVn/987-don-t-add-all-threads-to-main-space-each-time-we-create-a-new-site
> Don't add all Threads to main space each time we create a new site! 

- askbot/deps/django_authopenid/util.py
The existing code not handled properly the expiration time of
openid association handle. This caused a sign-in problems with
openstackid.org provider, meanwhile the launchpad provider was
not sensitive for this type of error.
Proper association issue time and lifetime variable assignment in
DjangoOpenIDStore.storeAssociation() function solves this issue
and requests a new association id when the existing one already
expired.
> Fix openid association expiration issue

- askbot/admin.py
Also allow searching by it - not easy because user has to know the iso code to search for
(eg. 'gb' for the UK, searching for 'uk' or 'United Kingdom' etc
won't work), but there are far too many possible values for a filter to
be practical.
> Show 'country' field in admin changelist for User model

- askbot/templates/widgets/ask_button.html
Newlines within the content of this anchor element cause any content included via an 'after' css pseudo element to slip down the page "to the
next line" in Chrome - see https://trello.com/c/QCto1N1x/116-big-ask-button-right-arrow-not-visible-in-chrome. We've fixed that instance via custom css quick fix, but this is the proper fix - we can make django ignore the leading and trailing whitespace in the template (whose purpose is to make the template more
readable) by judicious use of the hyphen character within the enclosing
if/else/endif template tags.
Generated markup before:
<a
id="askButton"
class="button"
href="/en/questions/ask/"
>
Ask Your Question
</a>
Generated markup after:
<a
id="askButton"
class="button"
href="/en/questions/ask/"
>Ask Your Question</a>
> Avoid unnecessary whitespace in html markup

- askbot/models/__init__.py
Fixes the following exception (from `askbot/models/__init__.py`):
```
Traceback (most recent call last):
File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
msg = self.format(record)
File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
return fmt.format(record)
File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
record.message = record.getMessage()
File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
msg = msg % self.args
TypeError: %d format: a number is required, not str
Logged from file __init__.py, line 261
```
Note that there are two connected issues to be fixed:
- `AVATAR_AUTO_GENERATE_SIZES` check always fails since a string will never be in a list of ints
- logging call raises an exception since we're trying to format a …
> Fix avatar size check/string formatting exception

- askbot/views/users.py
There's used `datetime` but not imported
> Update users.py - datetime is not imported but used

- askbot/deps/livesettings/views.py
Before it was a 500: NoneType has no attribute name
> Added 404 if settings is unfound

- askbot/setup_templates/settings.py
- askbot/setup_templates/settings.py.mustache
- askbot/templates/editors/rich_text.html
TINYMCE_PLUGINS are added to the template context (askbot/context.py) so using {{ settings.TINYMCE_PLUGINS }} in rich_text.html template raised KeyError.
'plugins' key was duplicated in TINYMCE_DEFAULT_CONFIG
> Fixes for TINYMCE_PLUGINS

- askbot/conf/forum_data_rules.py
- askbot/tests/utils.py
- askbot/tests/utils_tests.py
- askbot/utils/markup.py
I notice that `markdown2` has a hook system: https://github.com/trentm/python-markdown2/blob/fc438b576a2a6e82acebb0b2ac698e1e93a7b86e/lib/markdown2.py#L367
With the new option `MARKDOWN_CLASS`, I let admin choose their parser class. The can override the `markdown2.Markdown` and define this in this setting. Askbot will use their class with hooks.
I also PEP8-ize & add a test.
> Added custom markdown parser

- askbot/models/__init__.py
Due to a change in django-avatar updated versions will break certain views with the old util name. This change would import the new utils name and fall back if it fails.
Solves:
https://github.com/ASKBOT/askbot-devel/issues/593
and
https://github.com/ASKBOT/askbot-devel/issues/567
> Update import for django-avatar.utils

- askbot/conf/group_settings.py
Found a typo while I was helping translate askbot to Basque language.
"Enable group email adddresses" -> "Enable group email addresses"
> Fix typo: adddresses -> addresses

- askbot/conf/group_settings.py
- askbot/conf/leading_sidebar.py
- askbot/conf/sidebar_main.py
- askbot/conf/skin_general_settings.py
Ander Elortondo and Xalba from the Basque translation team Librezale spotted 4 strings that were missing spaces:
Use this area to enter content at the LEFT sidebarin HTML format. -> Use this area to enter content at the LEFT sidebar in HTML format.
Use this area to enter content at the BOTTOM of the sidebarin HTML format. -> Use this area to enter content at the BOTTOM of the sidebar in HTML format.
If selected, users can post to groups by email"group-name@domain.com" -> If selected, users can post to groups by email "group-name@domain.com"
"To change the logo, select new file, then submitthis whole form" -> "To change the logo, select new file, then submit this whole form"
> Add missing spaces

- askbot/__init__.py
Without this, `python setup.py develop` fails by trying to install the nonexistent `appconf` package.
> Use correct package name for appconf module (django-appconf)

- askbot/utils/html.py
The early return in `get_text_from_html` was added in 89e27a9719 for no very obvious reason, but leads to a giant CSS blob at the top of any plain-text email, in addition to worse line breaking. Since I don't know the rationale for removing it in that commit I'm not sure, but reverting the removal seems like the right thing.
> return to older html=>text email conversion

- askbot/deps/django_authopenid/util.py
- askbot/deps/livesettings/values.py
- askbot/forms.py
- askbot/management/commands/export_osqa.py
- askbot/management/commands/send_email_alerts.py
- askbot/skins/utils.py
`django.utils.datastructures.SortedDict` is deprecated in Django 1.7 and removed in 1.9.
> Use `collections.OrderedDict`

- askbot/doc/source/initial-configuration.rst
- tox.ini
The current execution of tox fails because of `--domain` being unsupported
> remove domain from other commands as it is unsupported

- askbot/deployment/__init__.py
- askbot/doc/source/initial-configuration.rst
- askbot/setup_templates/settings.py.mustache
Fixes #712 by allowing db host and db port to be configured with the cli utility `askbot-setup` for the purpose of configuring the docker image to work with external databases.
> allow configuration of DB host and port when running askbot-setup

- askbot/deps/django_authopenid/views.py
- askbot/forms.py
`django.forms.util` is renamed to ``django.forms.utils`
> Replace usage of `django.forms.util`

- Dockerfile
- askbot/container/prestart.py
* prestart.py would just go ahead and try to connect to a postgres DB.
When there isn't a Postgres DB this will yield an error
* Fixed example docker run command to prevent copy/paste frustration
> Do not imply that the docker image will be run with postgres

- askbot/deps/django_authopenid/util.py
- askbot/setup_templates/settings.py.jinja2
- askbot/skins/jinja2_environment.py
`OrderedDict` does not have a method `insert` (anymore?). However, a call to it is in the code that adds an authentication provider to `django_authopenid` through the app's `settings.py`. Having applied the first patch I was able to add a local OAuth2 provider without (further) touching the code of `django_authopenid`.
The second patch makes Jinja2 look for templates in a skin's directory. If I understand Jinja2's internals correctly, it first searches for a template in the skin dir and then its other dirs. Skins should now be able to replace individual template files. For my test setup I chose a value for `ASKBOT_EXTRA_SKINS_DIR` (i.e., an absolute path) that ends with `themes`. The layout of my test skin `mySkin` then looks like this:
themes/
themes/mySkin
themes/mySkin/jinja2 …
> Make Askbot flexible again

- askbot/deps/django_authopenid/util.py
The last patch introduced a bug where too many `'` are involved.
providers['mod.name']
should be
providers[mod.name]
> Bugfix! Variable was not resolved but used literally.

- askbot/deps/django_authopenid/views.py
! ldap_create_user had been updated to take a second param of the
request. Usages in django_authopenid/views.py were not taking this
change into account
> Django_autopenid provide missing param on create_user

- askbot/deps/django_authopenid/models.py
Because Foreign key implicitly means unique = True.
Django suggests using models.OneToOneField
django_authopenid.UserPasswordQueue.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
> using OneToOneField

- askbot/jinja2/user_inbox/responses.html
- askbot/views/users.py
* This fixes https://github.com/ASKBOT/askbot-devel/issues/846
* The issue is a name collision in Jinja
* renamed "messages" to "notifications", because the section that
displays them is called "notifications"
> Fix issue 846 

- askbot/deps/django_authopenid/views.py
Right now new user email validation shares the same subject with password recovery.
> Use a different subject for new user email validation.

- askbot/models/question.py
I believe this is a bug that is affecting my API endpoint. 
* [Here is an example question](https://answers.ros.org/api/v1/questions/308141/) that I recently marked as having an accepted answer. Note that `last_activity_at=1557194036`
* [Here is the accepted answer](https://answers.ros.org/api/v1/answers/322574/) which was `added_at=1557194036` (which is the same as the last activity)
This means that my action of accepting the answer is not reflected in the `last_activity_at` timestamp, which makes it difficult to keep track of which questions don't have accepted answers. 
I believe this PR should fix it, but I'm not 100% certain and haven't tested it locally yet.
> Set last activity when accepting answer

- askbot/templates/question.html
MIN_REP_TO_DELETE_OTHERS_COMMENTS was being used to check if delete button of questions should be hidden.
> Fix delete button being hidden when it shouldn't

- askbot/views/commands.py
Returning plain title caused showing incorrect title after editing it if a custom title renderer is used.
> Return rendered title instead of plain title

- askbot/deps/livesettings/models.py
As `loading.app_cache_ready` is deprecated.
> Use `apps.ready` instead of `loading.app_cache_ready`

- askbot/deployment/__init__.py
the code expects the option to be a string, but the cli parser had a validation checking whether it was an integer
closes #884
closes #891
> fix --db-engine option in askbot-setup

- askbot/deps/django_authopenid/ldap_auth.py
The custom function(s) should be loaded with the load_function function, instead of load_module.
Closes #905
> Fix custom LDAP_AUTH_FUNC_PATH and LDAP_CREATE_FUNC_PATH

- askbot/models/__init__.py
- askbot_requirements.txt
Error was introduced when django-avatar added support for rectangular avatars
Previously, method `get_primary_avatar` accepted only the `size` argument
Now, it has two args: `width` and `height`.
I took the simpler approach of assuming the avatars are always a square.
Ref: https://github.com/jazzband/django-avatar/commit/99a979b057e0a099eb1149eaac0956ce7a4b4fde
Closes #927
> Fix error when user has custom avatar

- .github/workflows/tests.yml
- askbot/tests/skip_test_reply_by_email.py
- askbot/tests/test_head_request_middleware.py
- askbot/tests/test_skins.py
- askbot_setup_test_inputs.txt
- requirements-tests.txt
Add tests that run for every github push.
This is a first step to better project health. I'd suggest a lot of things here if there were active development:
- moving to pip-tools or some other better package manager
- supporting running the unit tests directly from the tree instead of installing first
- moving on from the deprecated python setup tools to something supported
- fixing the broken unit tests that I commented out (hence fixing or removing lamson)
- etc..
P.S. I'd squash-commit this PR, it has lots of little tweaks while I was debugging.
> Add continuous integration tests
