ASKBOT/askbot-devel

askbot/media/js/group_messaging.js
askbot/templates/group_messaging/home.html

* We have to pass csrf token to the backend
* changed the html to represent the new javascript
@evgenyfadeev I did not know how you do forms in askbot, the markup right now is the same as in our verstion, maybe you want to adjust that a bit

add csrf token to form submit

---

askbot/forms.py

There is an error thrown when trying to enter a bigger number than 32767

limit the number to the allowed smallint value of 32767

---

askbot/views/readers.py

askbot_settings.get_setting_url('QA_SITE_SETTINGS', 'APP_URL') actually returns a link-tag
and you can not nest links in links

fix url to AppURL settings

---

askbot/media/js/live_search.js

When a tag gets appended to a list, it need to have an LI tag

wrap tag in li when appended to a ul

---

askbot/media/js/group_messaging.js

Use the same style for all error messages, and don't overwrite the label on error

dont overwrite label with error

---

askbot/media/js/group_messaging.js
askbot/media/js/live_search.js

Show en errormessage / hint that usernames have to be separated by comma

show error when multiple usernames are used

---

askbot/media/js/post.js

Make form validation highlight work for textarea in ask question

field is not always direct child of form-group

---

askbot/media/js/group_messaging.js
askbot/templates/group_messaging/senders_list.html
askbot/templates/group_messaging/threads_list.html

Make it possible to delete messages
Update message count on delete

add csrf to delete, and update inbox count

---

askbot/media/js/utils.js

otherwise result looks like "item1, item2, item3anditemlast"

add spaces around "and" in joinAsPhrase

---

askbot/media/js/group_messaging.js

in case you want to update it somewhere else on the page as well

trigger event when updating count

---

askbot/deps/group_messaging/models.py

https://docs.djangoproject.com/en/1.5/topics/signals/#preventing-duplicate-signals

use dispatch_uid to avoid duplicate signal sending

---

askbot/templates/embed/ask_by_widget.html

fixed editor js reference

---

askbot/media/js/post.js

This is useful if user wants to modify settings for validator on his side

additional trigger on question retagger after validation is set up

---

askbot/media/wmd/wmd.js

also cleaned up some trailing whitespace
actual change on line 444

adds ability to run arbitrary code after wmd popup is created

---

askbot/media/js/post.js

It is not possible to add a question/answer that has no content, but atm it's not validated in frontend.

require fields in question/answer forms

---

askbot/admin.py

http://knowledgepoint.org/admin/askbot/postrevision/ -
https://trello.com/c/BefXVlQ4/731-postrevision-admin-list-improvements

Allow searching by thread name and filtering by author in PostRevision admin

---

askbot/models/__init__.py

The condition for the IF branches is inverted.

Return the correct primary language based on the multilingual setting

---

askbot/views/writers.py

it helps if you want to display additional label if a particular user is and admin or mod

add information about user status in generate_comments_json

---

askbot/models/question.py
askbot/views/api_v1.py

Return accepted answer id

---

askbot/media/js/post.js

these are helpful if the user wants to track specific events through google analytics or comparable solution

add more events

---

askbot/migrations/0190_auto__chg_field_anonymousquestion_ip_addr__chg_field_anonymousanswer_i.py
askbot/models/base.py
askbot/models/post.py

Currently IPv6 addresses cannot be saved to ip_addr fields in Post, AnonymousQuestion and AnonymousAnswer models if there's size limit in the database. It's true at least with MySQL.

Added IPv6 clients support

---

askbot/deps/group_messaging/migrations/0004_auto__chg_field_message_senders_info.py
askbot/deps/group_messaging/models.py
askbot/views/readers.py

* changed sender_info field to textfield
* fixes unicode error on reader

change from charfield to textfield

---

askbot/tests/api_v1_tests.py
askbot/views/api_v1.py

Adding gold, silver and bronze medal count to User API.

Add medal info to user api

---

askbot/views/widgets.py

https://github.com/ASKBOT/askbot-devel/commit/f14d493fc830689b2bc7a6706ffc0908df5f80ca.

URGENT! Fix syntax error introduced at

---

askbot/admin.py

Handy for testing things like Thread.last_activity_at updating.

Show full timestamps (including seconds) in django admin screens.

---

askbot/forms.py

Fixed missing site ID from widget forms
https://trello.com/c/cMx1Zw2z/949-editing-widgets-causes-internal-server-error

Edit widget fix

---

askbot/media/js/post.js

This change has already been made to the master branch
c57e765a4b535d94533930369caeabf08031f7ae

Made title required for client side validation

---

askbot/tests/question_views_tests.py

Update test case class' setUp methods now that an user must have a primary group in order to be able to post privately (since May 2013). Also, allow tests to still work
in instances where site is multilingual. Then some little
fixes/improvements such as checking assumptions at the start of each
test, squashing multiple requests into one when there's a redirect, and
ensuring that failures will give more useful error messages (eg.
checking that a checkbox does exist in response.content before checking
its value).

Fixes (and some improvements) to question views tests

---

askbot/admin.py

* new column called 'Has tags' that lists the names of the Tags assigned
to each Thread.
* Thread search now includes names of all Tags assigned to each Thread.
* Thread view contains an inline table to show its Tags

Changes to django admin for Threads:

---

askbot/management/commands/askbot_setup_sites.py

of KP) so that all existing sites see changes to
ASKBOT_PARTNER_SITE_IDS.

Added note to reload/restart all webserver processes (uwsgi ones in case

---

askbot/conf/login_providers.py

Fixed typo

---

askbot/doc/source/upgrade.rst

:: makes a code block, breaks the table

Fix table formatting in upgrade.rst

---

askbot/admin.py
askbot/models/user.py

Improve Activity model & ActivityAdmin

---

askbot/admin.py
askbot/models/repute.py

- PEP8ize models/repute.py
- Improve ModelAdmin of these models
- Added translation

Improve repute admin and models

---

askbot/templates/badges.html

Now, badges, description and awarded are sorted in columns.

Sort badges views with table

---

askbot/startup_procedures.py

I made an error here: https://github.com/ASKBOT/askbot-devel/commit/fb28d60e6018deaad06347e266afe6e1865e5d3e#diff-4461ccb6e04bef011e053d4be0855d7eL935
There's was a `False` condition if `ASKBOT_MULTILINGUAL` is not set.
But we want to test if it's true or false. Undefined is good.

Fixed startup bug

---

askbot/bin/rebuildlocales.py

Should we add `if __name__ == '__main__'` in this kind of script ?

PEP8-ize bin/rebuildlocales.py

---

askbot/forms.py
askbot/tests/form_tests.py

I made a mistake when PEP8-ized.
I fixed it with tests.
Sorry ...

Fixed tag matching

---

askbot/tests/factories.py

Hello @evgenyfadeev 
What do you think about use Factory Boy ?
I saw that you're using custom methods of `AskBotTestCase`, I think we could ever use them but Factory Boy allows a simple way to create many objects simply and eases new users' contributions with a minimal documentation.

Factory Boy

---

askbot/models/message.py
askbot/models/user.py
askbot/tests/factories.py

And also make some PEP8-ization

Added more Factories

---

askbot/tests/utils_tests.py
askbot/utils/html.py

I created my custom `Markdown`, but wasn't able to add attribute "id" to tags, neither add iframe tags (useful for videos).
I also PEP8-ized `askbot/utils/html.py` and added tests to my feature

[WIP] Added settings to configure allowed elements & attrs in HTML sanitization

---

askbot/doc/source/optional-modules.rst

We added S3 integration support in our deployment. If the following AWS params are defined as environmental variables, the corresponding S3 bucket will be used. Otherwise the local storage is used - just like before:
$ export STORAGE_BUCKET_NAME=BUCKET_NAEM
$ export ACCESS_KEY_ID=XXXXXXXXXXXXXXXX
$ export SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXX
The problem we encountered was with media files. In a auto scaling group, the media files used be saved on a shared S3 bucket instead of local. The documentation should be updated to mention that these env variables can be set to to use S3.

Add S3 integration support for Askbot

---

askbot/models/base.py

I just wanted to fix a typo, but the sentence seemed awkward.

Docstring reword in base.py

---

askbot/search/postgresql/__init__.py

in case that the postgres full text search does not returns results and the search query length is less than 5 chars.

Allows fallback to Django ORM search

---

askbot/views/users.py

The check let through unauthenticated users and caused error later on in the code

Fix permission check on user moderation page

---

askbot/models/user.py

Add standard django user method get_full_name to MockUser

Add standard django user method get_full_name to MockUser

---

Dockerfile

askbot-setup command doesn't support '--domain' option.

Remove the option isn't recognized by askbot-setup in the Dockerfile

---

askbot/management/commands/create_tag_synonyms.py
askbot/management/commands/rename_tags.py
askbot/utils/console.py

Extract `decode_input` and handle the case when `sys.stdin.encoding` is `None`.

Handle sys.stdin.encoding is None

---

askbot/tests/test_page_load.py

As `failUnless` is deprecated.

Use `assertTrue` instead of `failUnless`

---

askbot/deps/livesettings/functions.py
askbot/management/commands/merge_users.py

Fix raise exception

---

askbot/deps/django_authopenid/ldap_auth.py
askbot/deps/django_authopenid/util.py
askbot/deps/django_authopenid/views.py
askbot/deps/livesettings/functions.py
askbot/deps/livesettings/models.py
askbot/deps/livesettings/values.py
askbot/forms.py
askbot/importers/stackexchange/management/commands/load_stackexchange.py
askbot/importers/zendesk/management/commands/import_zendesk.py
askbot/mail/__init__.py
askbot/mail/lamson_handlers.py
askbot/management/commands/export_osqa.py
askbot/management/commands/merge_users.py
askbot/management/commands/rename_tags.py
askbot/management/commands/subscribe_everyone.py
askbot/models/__init__.py
askbot/patches/django_patches.py
askbot/startup_procedures.py
askbot/tasks.py
askbot/utils/akismet_utils.py
askbot/utils/decorators.py
askbot/utils/hasher.py
askbot/utils/path.py
askbot/views/commands.py
askbot/views/emails.py
askbot/views/readers.py
askbot/views/users.py
askbot/views/writers.py

Change except statements with named exceptions.

---

askbot/media/js/group_messaging.js
askbot/media/js/post.js
askbot/templates/user_inbox/messages.html
askbot/templates/widgets/proxy_author_fields.html

it was failing when service url prefix is set

fix autocomplete for user infos in group messaging/post on behalf

---

askbot/management/commands/generate_post_snippets.py

Post.get_snippet() uses Post.html, therefore it should be updated after html

Reverse update order of summary and html

---

askbot/__init__.py
askbot/conf/access_control.py
askbot/conf/badges.py
askbot/conf/email.py
askbot/conf/flatpages.py
askbot/conf/login_providers.py
askbot/conf/settings_wrapper.py
askbot/forms.py
askbot/mail/__init__.py
askbot/models/__init__.py
askbot/models/question.py
askbot/tests/test_markup.py
askbot/urls.py
askbot/views/commands.py
askbot/views/moderation.py
askbot/views/users.py
askbot_requirements.txt
testproject/testproject/settings.py

This is the next PR in a series to make the 0.11.x branch compatible to Django 2.2

Upgrade to Django 2.1

---

askbot/management/commands/add_admin.py

This is the next PR in a series to make the 0.11.x branch compatible to Django 2.2

Fix add_admin command

---

README.rst
askbot/__init__.py
askbot/doc/source/contributors.rst
askbot/doc/source/dependencies.rst
askbot/doc/source/deployment.rst
askbot/doc/source/install.rst
askbot/doc/source/optional-modules.rst
askbot/doc/source/upgrade.rst

This is the next PR in a series to make the 0.11.x branch compatible to Django 2.2

Updated documentation for Python 3 and Django 2.2

---

askbot/context.py
askbot/jinja2/widgets/search_bar.html
askbot/search/state_manager.py
askbot/setup_templates/settings.py
askbot/setup_templates/settings.py.mustache
askbot/skins/template_backends.py
askbot/startup_procedures.py
askbot/templatetags/extra_filters_jinja.py
askbot/utils/file_utils.py
askbot/views/users.py
askbot_requirements.txt
testproject/testproject/settings.py

This is the next PR in a series to make the 0.11.x branch compatible to Django 2.2
A PR that fixes deploying Askbot is still waiting

Upgrade to Django 2.2

---

askbot/deployment/__init__.py
askbot/tests/test_management_commands.py
askbot/tests/test_page_load.py
requirements-tests.txt
tox.ini

Small stuff w.r.t. testing and old version tests

Tests and testing 0.11.x

---

askbot/doc/source/api.rst
askbot/urls.py
askbot/views/api_v1.py

Following up on an [old feature request](https://askbot.org/en/question/12881/adding-answer-functionality-to-the-api/) and some [other](https://github.com/ASKBOT/askbot-devel/pull/334) [PRs](https://github.com/ASKBOT/askbot-devel/pull/335)
This implements new functionality to get information about single answers. 
(There's also one formatting change to the documentation to get it to render properly)
The code is untested, but I wanted to see if I was still on the right track.

Answers API

---

setup.py

Fixed mentions of MySQL InnoDB not supporting FTS

---

askbot/importers/stackexchange/management/__init__.py
askbot/management/commands/export_osqa.py
askbot/models/__init__.py
askbot/search/haystack/indexes.py

Use `django.apps.apps.get_model` instead of `django.db.models.get_model`

Replace usage of `django.db.models.get_model`

---

askbot/deps/django_authopenid/util.py

Remove some unused imports and remove `provider_name` as not need for `object()`.

Fix `object() takes no parameters`

---

askbot/admin.py
askbot/models/user_profile.py

1. Add UserProfile to UserAdmin
2. Add MarkedTag to UserAdmin
3. Add EmailFeedSettingAdmin
We're relying heavily email notifications. This helped me finding things out.
I.e.,  "Im not getting any email notifications for the whole askbot"
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

Add email settings to the Admin page:

---

askbot/migrations/0014_populate_askbot_roles.py

This is probably not the correct way of doing it, but it's working for me, maybe someone else might find it helpful.

Fix migration 0014 not working on live data.

---

askbot/__init__.py
askbot/templatetags/extra_filters_jinja.py

allow usage of new jinja version

---

README.md

remove duplicate section in README

---

.github/workflows/tests.yml
.pre-commit-config.yaml
README.md
askbot/management/commands/askbot_add_osqa_content.py
pyproject.toml

Also run it in the github tests.

Add basic, mostly empty pre-commit and ruff

---

askbot/models/__init__.py

Fix moderators disabling administrators. 
